import {
  Appointment,
  AttendanceRecord,
  ClinicSettings,
  Contact,
  Employee,
  Expense,
  PharmacyItem,
  SalaryRecord,
  Sale,
  Treatment,
} from "@/types";

export const defaultSettings: ClinicSettings = {
  clinicName: "SHEZI AESTHETICS",
  tagline: "Advanced Medical Aesthetics & Dermatology",
  phone: "+1 (555) 839-2041",
  email: "concierge@sheziaesthetics.com",
  address: "450 Luxury Boulevard, Suite 800, Beverly Hills, CA 90210",
  currencySymbol: "Rs. ",
  taxRatePercent: 8.5,
  workingHours: {
    open: "09:00",
    close: "19:00",
  },
};

// 1. Exactly 3 Employees (1 Admin, 1 Manager, 1 Staff User)
export const seedEmployees: Employee[] = [
  {
    employeeId: "emp-001",
    name: "Sheraz khan",
    email: "sherazkhan@admin.com",
    phone: "+1 (555) 234-5678",
    designation: "Lead Aesthetic Physician",
    salary: 9500,
    shiftStart: "09:00",
    shiftEnd: "18:00",
    joiningDate: "2023-01-15",
    isActive: true,
    specialization: "Injectables, Facial Sculpting & Thread Lifts",
    role: "admin",
    password: "admin@321",
  },
  {
    employeeId: "emp-002",
    name: "Alexander Wright",
    email: "salar@gmail.com",
    phone: "+1 (555) 678-9012",
    designation: "Clinic Manager",
    salary: 5800,
    shiftStart: "08:30",
    shiftEnd: "17:30",
    joiningDate: "2022-11-01",
    isActive: true,
    specialization: "Clinic Operations, Financials & Patient Experience",
    role: "manager",
    password: "manager123",
  },
  {
    employeeId: "emp-003",
    name: "Isabella Rossi",
    email: "user@gmail.com",
    phone: "+1 (555) 789-0123",
    designation: "Front Desk Receptionist",
    salary: 3400,
    shiftStart: "08:30",
    shiftEnd: "17:00",
    joiningDate: "2024-02-15",
    isActive: true,
    specialization: "Patient Concierge, Scheduling & Billing",
    role: "user",
    password: "user123",
  },
];

// 2. Exactly 3 Medical & Aesthetic Treatments
export const seedTreatments: Treatment[] = [
  {
    treatmentId: "trt-001",
    name: "HydraFacial Platinum Luxe",
    description: "Deep cleansing, vortex extraction, lymphatic drainage, and peptide infusion with custom LED therapy.",
    price: 295,
    costPrice: 65,
    duration: 60,
    category: "Facials & Peels",
    isActive: true,
  },
  {
    treatmentId: "trt-002",
    name: "Botox Cosmetic (3 Target Areas)",
    description: "FDA-approved neuromodulator injection for forehead lines, crow's feet, and glabellar lines.",
    price: 480,
    costPrice: 220,
    duration: 30,
    category: "Injectables & Fillers",
    isActive: true,
  },
  {
    treatmentId: "trt-003",
    name: "Juvederm Voluma Cheek & Jaw Contour",
    description: "Hyaluronic acid dermal filler for mid-face volume restoration and sharp jawline definition.",
    price: 750,
    costPrice: 290,
    duration: 60,
    category: "Injectables & Fillers",
    isActive: true,
  },
];

// 3. Exactly 3 Contacts / Patients
export const seedContacts: Contact[] = [
  {
    contactId: "cnt-001",
    name: "Victoria Sterling",
    phone: "+1 (555) 901-2345",
    email: "victoria.sterling@beverly.com",
    address: "710 Elm Way, Beverly Hills, CA",
    dob: "1988-04-12",
    gender: "Female",
    skinType: "Combination",
    allergies: "None",
    totalVisits: 6,
    totalSpent: 3450,
    lastVisit: "2026-09-02",
    notes: "VIP Client. Prefers morning appointments with Dr. Sheraz Khan. Sensitive to strong fragrances.",
    createdAt: "2024-01-10",
  },
  {
    contactId: "cnt-002",
    name: "Julian Montgomery",
    phone: "+1 (555) 812-3456",
    email: "j.montgomery@venture.io",
    address: "1200 Ocean Ave, Santa Monica, CA",
    dob: "1982-11-29",
    gender: "Male",
    skinType: "Oily",
    allergies: "Latex (Use nitrile gloves)",
    totalVisits: 4,
    totalSpent: 2680,
    lastVisit: "2026-08-28",
    notes: "Laser resurfacing maintenance. Uses Heliocare SPF 50 daily.",
    createdAt: "2024-03-15",
  },
  {
    contactId: "cnt-003",
    name: "Camilla Rodriguez",
    phone: "+1 (555) 723-4567",
    email: "camilla.r@studio.design",
    address: "340 Melrose Ave, West Hollywood, CA",
    dob: "1994-07-08",
    gender: "Female",
    skinType: "Dry",
    allergies: "Aspirin / Salicylic acid",
    totalVisits: 8,
    totalSpent: 4120,
    lastVisit: "2026-09-04",
    notes: "Monthly HydraFacial devotee. Loves peptide boosters.",
    createdAt: "2023-11-20",
  },
];

// 4. Exactly 3 Appointments
export const seedAppointments: Appointment[] = [
  {
    appointmentId: "apt-101",
    customerName: "Victoria Sterling",
    customerPhone: "+1 (555) 901-2345",
    customerEmail: "victoria.sterling@beverly.com",
    procedureId: "trt-002",
    procedureName: "Botox Cosmetic (3 Target Areas)",
    employeeId: "emp-001",
    employeeName: "Sheraz khan",
    appointmentDate: "2026-09-06",
    appointmentTime: "10:30",
    status: "confirmed",
    createdBy: "Isabella Rossi",
    price: 480,
    notes: "Follow up touch-up for forehead lines.",
  },
  {
    appointmentId: "apt-102",
    customerName: "Camilla Rodriguez",
    customerPhone: "+1 (555) 723-4567",
    customerEmail: "camilla.r@studio.design",
    procedureId: "trt-001",
    procedureName: "HydraFacial Platinum Luxe",
    employeeId: "emp-001",
    employeeName: "Sheraz khan",
    appointmentDate: "2026-09-06",
    appointmentTime: "11:45",
    status: "in-progress",
    createdBy: "Isabella Rossi",
    price: 295,
    notes: "Include red LED light therapy booster.",
  },
  {
    appointmentId: "apt-103",
    customerName: "Julian Montgomery",
    customerPhone: "+1 (555) 812-3456",
    customerEmail: "j.montgomery@venture.io",
    procedureId: "trt-003",
    procedureName: "Juvederm Voluma Cheek & Jaw Contour",
    employeeId: "emp-001",
    employeeName: "Sheraz khan",
    appointmentDate: "2026-09-06",
    appointmentTime: "14:00",
    status: "scheduled",
    createdBy: "Isabella Rossi",
    price: 750,
    notes: "Mid-face volume restoration and contour.",
  },
];

// 5. Exactly 3 Pharmacy / Inventory Products
export const seedPharmacy: PharmacyItem[] = [
  {
    itemId: "phm-001",
    name: "Botox Cosmetic 100U Vials",
    category: "Injectables & Toxins",
    quantity: 25,
    unit: "vials",
    minThreshold: 5,
    costPrice: 220,
    sellingPrice: 480,
    expiryDate: "2027-04-30",
    supplier: "Allergan Aesthetics Direct",
    batchNumber: "AL-89211",
  },
  {
    itemId: "phm-002",
    name: "Juvederm Voluma XC (1ml Syringe)",
    category: "Injectables & Toxins",
    quantity: 18,
    unit: "syringes",
    minThreshold: 6,
    costPrice: 290,
    sellingPrice: 750,
    expiryDate: "2027-02-15",
    supplier: "AbbVie / Allergan Medical",
    batchNumber: "JV-44901",
  },
  {
    itemId: "phm-003",
    name: "SkinCeuticals C E Ferulic (30ml)",
    category: "Skincare & Cosmeceuticals",
    quantity: 30,
    unit: "bottles",
    minThreshold: 8,
    costPrice: 95,
    sellingPrice: 182,
    expiryDate: "2027-08-01",
    supplier: "L'Oréal Dermatological Beauty",
    batchNumber: "SC-30219",
  },
];

// 6. Exactly 3 Sales / Invoices (Covering Procedure, Medicine, and Mixed Sales)
export const seedSales: Sale[] = [
  {
    saleId: "sal-001",
    invoiceNumber: "INV-2026-901",
    appointmentId: "apt-101",
    customerName: "Victoria Sterling",
    customerPhone: "+1 (555) 901-2345",
    saleType: "mixed",
    procedureId: "trt-003",
    procedureName: "Juvederm Voluma Cheek & Jaw Contour + 1x SkinCeuticals CE Ferulic",
    items: [
      {
        id: "trt-003",
        name: "Juvederm Voluma Cheek & Jaw Contour",
        type: "procedure",
        quantity: 1,
        unitPrice: 750,
        costPrice: 290,
        totalAmount: 750,
        totalCost: 290,
        profit: 460,
      },
      {
        id: "phm-003",
        name: "SkinCeuticals C E Ferulic (30ml)",
        type: "medicine",
        quantity: 1,
        unitPrice: 182,
        costPrice: 95,
        totalAmount: 182,
        totalCost: 95,
        profit: 87,
        unit: "bottles",
        batchNumber: "SC-30219",
      },
    ],
    amount: 932,
    discount: 50,
    netAmount: 882,
    totalCost: 385,
    profit: 497,
    paymentMethod: "credit_card",
    saleDate: "2026-09-02",
    recordedBy: "Isabella Rossi",
    notes: "VIP Member loyalty discount applied.",
  },
  {
    saleId: "sal-002",
    invoiceNumber: "INV-2026-902",
    appointmentId: "apt-102",
    customerName: "Camilla Rodriguez",
    customerPhone: "+1 (555) 723-4567",
    saleType: "procedure",
    procedureId: "trt-001",
    procedureName: "HydraFacial Platinum Luxe",
    items: [
      {
        id: "trt-001",
        name: "HydraFacial Platinum Luxe",
        type: "procedure",
        quantity: 1,
        unitPrice: 295,
        costPrice: 65,
        totalAmount: 295,
        totalCost: 65,
        profit: 230,
      },
    ],
    amount: 295,
    discount: 25,
    netAmount: 270,
    totalCost: 65,
    profit: 205,
    paymentMethod: "cash",
    saleDate: "2026-09-03",
    recordedBy: "Isabella Rossi",
    notes: "Full luxury facial with LED booster.",
  },
  {
    saleId: "sal-003",
    invoiceNumber: "INV-2026-903",
    appointmentId: "apt-103",
    customerName: "Julian Montgomery",
    customerPhone: "+1 (555) 812-3456",
    saleType: "medicine",
    procedureId: "phm-001",
    procedureName: "Botox Cosmetic 100U Vials (2 Vials)",
    items: [
      {
        id: "phm-001",
        name: "Botox Cosmetic 100U Vials",
        type: "medicine",
        quantity: 2,
        unitPrice: 480,
        costPrice: 220,
        totalAmount: 960,
        totalCost: 440,
        profit: 520,
        unit: "vials",
        batchNumber: "AL-89211",
      },
    ],
    amount: 960,
    discount: 0,
    netAmount: 960,
    totalCost: 440,
    profit: 520,
    paymentMethod: "credit_card",
    saleDate: "2026-09-04",
    recordedBy: "Alexander Wright",
    notes: "Prescription takeaway dispensed.",
  },
];

// 7. Exactly 3 Expenses
export const seedExpenses: Expense[] = [
  {
    expenseId: "exp-001",
    category: "Rent & Premises",
    description: "Monthly Beverly Hills Suite Lease & Building Maintenance",
    amount: 5200,
    expenseDate: "2026-09-01",
    recordedBy: "Alexander Wright",
    vendor: "Rodeo Luxury Properties LLC",
  },
  {
    expenseId: "exp-002",
    category: "Medical Supplies & Serums",
    description: "Restock Allergan Botox 100U & Juvederm Voluma",
    amount: 3800,
    expenseDate: "2026-08-29",
    recordedBy: "Alexander Wright",
    vendor: "Allergan Pharmaceuticals Supply",
  },
  {
    expenseId: "exp-003",
    category: "Marketing & Social Media",
    description: "Google Ads Aesthetic Search & Instagram Influencer Campaign",
    amount: 1450,
    expenseDate: "2026-08-25",
    recordedBy: "Alexander Wright",
    vendor: "Meta & Google Ads",
  },
];

// 8. Exactly 3 Attendance Records (one for each employee)
export const seedAttendance: AttendanceRecord[] = [
  {
    attendanceId: "att-001",
    employeeId: "emp-001",
    employeeName: "Sheraz khan",
    date: "2026-09-06",
    status: "present",
    checkIn: "08:55",
    checkOut: "18:05",
    markedBy: "Alexander Wright",
    remarks: "On-time arrival for surgical consults",
  },
  {
    attendanceId: "att-002",
    employeeId: "emp-002",
    employeeName: "Alexander Wright",
    date: "2026-09-06",
    status: "present",
    checkIn: "08:25",
    checkOut: "17:40",
    markedBy: "Alexander Wright",
    remarks: "Opening clinic manager shift",
  },
  {
    attendanceId: "att-003",
    employeeId: "emp-003",
    employeeName: "Isabella Rossi",
    date: "2026-09-06",
    status: "present",
    checkIn: "08:28",
    checkOut: "17:05",
    markedBy: "Alexander Wright",
    remarks: "Front desk reception on schedule",
  },
];

// 9. Exactly 3 Salary Records (one for each employee)
export const seedSalaries: SalaryRecord[] = [
  {
    salaryId: "sal-emp-001-2026-08",
    employeeId: "emp-001",
    employeeName: "Sheraz khan",
    designation: "Lead Aesthetic Physician",
    month: "2026-08",
    baseSalary: 9500,
    workingDays: 26,
    presentDays: 26,
    absentDays: 0,
    leaveDays: 0,
    dailyRate: 365.38,
    deductions: 0,
    bonus: 500,
    netPay: 10000,
    status: "paid",
    paymentDate: "2026-08-31",
    paymentMethod: "bank_transfer",
    recordedBy: "Alexander Wright",
    payslipNumber: "PAY-202608-0001",
    remarks: "Full attendance plus monthly clinical excellence bonus.",
  },
  {
    salaryId: "sal-emp-002-2026-08",
    employeeId: "emp-002",
    employeeName: "Alexander Wright",
    designation: "Clinic Manager",
    month: "2026-08",
    baseSalary: 5800,
    workingDays: 26,
    presentDays: 26,
    absentDays: 0,
    leaveDays: 0,
    dailyRate: 223.08,
    deductions: 0,
    bonus: 0,
    netPay: 5800,
    status: "paid",
    paymentDate: "2026-08-31",
    paymentMethod: "bank_transfer",
    recordedBy: "Sheraz khan",
    payslipNumber: "PAY-202608-0002",
    remarks: "Managerial payroll processed.",
  },
  {
    salaryId: "sal-emp-003-2026-08",
    employeeId: "emp-003",
    employeeName: "Isabella Rossi",
    designation: "Front Desk Receptionist",
    month: "2026-08",
    baseSalary: 3400,
    workingDays: 26,
    presentDays: 26,
    absentDays: 0,
    leaveDays: 0,
    dailyRate: 130.77,
    deductions: 0,
    bonus: 100,
    netPay: 3500,
    status: "paid",
    paymentDate: "2026-08-31",
    paymentMethod: "bank_transfer",
    recordedBy: "Alexander Wright",
    payslipNumber: "PAY-202608-0003",
    remarks: "Patient satisfaction and rebooking bonus.",
  },
];
