import {
  Appointment,
  AttendanceRecord,
  ClinicSettings,
  Contact,
  Employee,
  Expense,
  PharmacyItem,
  SalaryRecord,
  Sale,
  Treatment,
} from "@/types";

export const defaultSettings: ClinicSettings = {
  clinicName: "SHEZI AESTHETICS",
  tagline: "Advanced Medical Aesthetics & Dermatology",
  phone: "+1 (555) 839-2041",
  email: "concierge@sheziaesthetics.com",
  address: "450 Luxury Boulevard, Suite 800, Beverly Hills, CA 90210",
  currencySymbol: "Rs. ",
  taxRatePercent: 8.5,
  workingHours: {
    open: "09:00",
    close: "19:00",
  },
};

export const seedEmployees: Employee[] = [
  {
    employeeId: "emp-001",
    name: "Sheraz khan",
    email: "sherazkhan@admin.com",
    phone: "+1 (555) 234-5678",
    designation: "Lead Aesthetic Physician",
    salary: 9500,
    shiftStart: "09:00",
    shiftEnd: "18:00",
    joiningDate: "2023-01-15",
    isActive: true,
    specialization: "Injectables, Facial Sculpting & Thread Lifts",
    role: "admin",
    password: "admin@321",
  },
  {
    employeeId: "emp-002",
    name: "Dr. Marcus Chen, M.D.",
    email: "dr.chen@sheziaesthetics.com",
    phone: "+1 (555) 345-6789",
    designation: "Cosmetic Dermatologist",
    salary: 9000,
    shiftStart: "10:00",
    shiftEnd: "19:00",
    joiningDate: "2023-03-01",
    isActive: true,
    specialization: "Laser Resurfacing & Advanced Skin Rejuvenation",
    role: "admin",
  },
  {
    employeeId: "emp-003",
    name: "Sophia Laurent",
    email: "sophia@sheziaesthetics.com",
    phone: "+1 (555) 456-7890",
    designation: "Senior Aesthetician",
    salary: 4500,
    shiftStart: "09:00",
    shiftEnd: "17:30",
    joiningDate: "2023-06-10",
    isActive: true,
    specialization: "HydraFacial, Chemical Peels & Dermaplaning",
    role: "user",
  },
  {
    employeeId: "emp-004",
    name: "Maya Patel, R.N.",
    email: "maya@sheziaesthetics.com",
    phone: "+1 (555) 567-8901",
    designation: "Registered Aesthetic Nurse",
    salary: 4800,
    shiftStart: "09:00",
    shiftEnd: "18:00",
    joiningDate: "2023-09-01",
    isActive: true,
    specialization: "PRP Therapy, Microneedling & IV Drips",
    role: "user",
  },
  {
    employeeId: "emp-005",
    name: "Alexander Wright",
    email: "salar@gmail.com",
    phone: "+1 (555) 678-9012",
    designation: "Clinic Manager",
    salary: 5800,
    shiftStart: "08:30",
    shiftEnd: "17:30",
    joiningDate: "2022-11-01",
    isActive: true,
    specialization: "Clinic Operations, Financials & Patient Experience",
    role: "manager",
    password: "manager123",
  },
  {
    employeeId: "emp-006",
    name: "Isabella Rossi",
    email: "user@gmail.com",
    phone: "+1 (555) 789-0123",
    designation: "Front Desk Receptionist",
    salary: 3400,
    shiftStart: "08:30",
    shiftEnd: "17:00",
    joiningDate: "2024-02-15",
    isActive: true,
    specialization: "Patient Concierge, Scheduling & Billing",
    role: "user",
    password: "user123",
  },
];

export const seedTreatments: Treatment[] = [
  {
    treatmentId: "trt-001",
    name: "HydraFacial Platinum Luxe",
    description: "Deep cleansing, vortex extraction, lymphatic drainage, and peptide infusion with custom LED therapy.",
    price: 295,
    duration: 60,
    category: "Facials & Peels",
    isActive: true,
  },
  {
    treatmentId: "trt-002",
    name: "Botox Cosmetic (3 Target Areas)",
    description: "FDA-approved neuromodulator injection for forehead lines, crow's feet, and glabellar lines.",
    price: 480,
    duration: 30,
    category: "Injectables & Fillers",
    isActive: true,
  },
  {
    treatmentId: "trt-003",
    name: "Juvederm Voluma Cheek & Jaw Contour",
    description: "Hyaluronic acid dermal filler for mid-face volume restoration and sharp jawline definition.",
    price: 750,
    duration: 60,
    category: "Injectables & Fillers",
    isActive: true,
  },
  {
    treatmentId: "trt-004",
    name: "Fractional CO2 Laser Resurfacing",
    description: "Ablative micro-beam laser treatment to dramatically reduce acne scars, hyperpigmentation, and deep wrinkles.",
    price: 890,
    duration: 90,
    category: "Laser & IPL",
    isActive: true,
  },
  {
    treatmentId: "trt-005",
    name: "PRP Vampire Facial & Microneedling",
    description: "Autologous platelet-rich plasma microneedled into dermis for collagen synthesis and pore refinement.",
    price: 580,
    duration: 75,
    category: "Skin Tightening",
    isActive: true,
  },
  {
    treatmentId: "trt-006",
    name: "Medical Grade TCA Jessner Peel",
    description: "Targeted acid peel for melasma, sun damage, and uneven texture.",
    price: 240,
    duration: 45,
    category: "Facials & Peels",
    isActive: true,
  },
  {
    treatmentId: "trt-007",
    name: "Laser Hair Reduction (Full Legs & Underarms)",
    description: "Triple-wavelength diode laser with chilled sapphire tip for pain-free permanent reduction.",
    price: 380,
    duration: 60,
    category: "Laser & IPL",
    isActive: true,
  },
  {
    treatmentId: "trt-008",
    name: "Profhilo Bio-Remodeling Hydration",
    description: "Ultra-pure hyaluronic acid bioremodeling treatment stimulating 4 types of collagen and elastin.",
    price: 520,
    duration: 45,
    category: "Injectables & Fillers",
    isActive: true,
  },
];

export const seedContacts: Contact[] = [
  {
    contactId: "cnt-001",
    name: "Victoria Sterling",
    phone: "+1 (555) 901-2345",
    email: "victoria.sterling@beverly.com",
    address: "710 Elm Way, Beverly Hills, CA",
    dob: "1988-04-12",
    gender: "Female",
    skinType: "Combination",
    allergies: "None",
    totalVisits: 6,
    totalSpent: 3450,
    lastVisit: "2026-09-02",
    notes: "VIP Client. Prefers morning appointments with Dr. Vance. Sensitive to strong fragrances.",
    createdAt: "2024-01-10",
  },
  {
    contactId: "cnt-002",
    name: "Julian Montgomery",
    phone: "+1 (555) 812-3456",
    email: "j.montgomery@venture.io",
    address: "1200 Ocean Ave, Santa Monica, CA",
    dob: "1982-11-29",
    gender: "Male",
    skinType: "Oily",
    allergies: "Latex (Use nitrile gloves)",
    totalVisits: 4,
    totalSpent: 2680,
    lastVisit: "2026-08-28",
    notes: "Laser resurfacing maintenance. Uses Heliocare SPF 50 daily.",
    createdAt: "2024-03-15",
  },
  {
    contactId: "cnt-003",
    name: "Camilla Rodriguez",
    phone: "+1 (555) 723-4567",
    email: "camilla.r@studio.design",
    address: "340 Melrose Ave, West Hollywood, CA",
    dob: "1994-07-08",
    gender: "Female",
    skinType: "Dry",
    allergies: "Aspirin / Salicylic acid",
    totalVisits: 8,
    totalSpent: 4120,
    lastVisit: "2026-09-04",
    notes: "Monthly HydraFacial devotee. Loves peptide boosters.",
    createdAt: "2023-11-20",
  },
  {
    contactId: "cnt-004",
    name: "Liam O'Connor",
    phone: "+1 (555) 634-5678",
    email: "liam.oconnor@media.net",
    address: "880 Sunset Blvd, Los Angeles, CA",
    dob: "1990-02-18",
    gender: "Male",
    skinType: "Sensitive",
    allergies: "None",
    totalVisits: 3,
    totalSpent: 1140,
    lastVisit: "2026-08-20",
    notes: "PRP hair therapy and botox for forehead.",
    createdAt: "2024-05-02",
  },
  {
    contactId: "cnt-005",
    name: "Seraphina Thorne",
    phone: "+1 (555) 545-6789",
    email: "seraphina@thorne-estates.com",
    address: "220 Bel Air Rd, Los Angeles, CA",
    dob: "1985-09-23",
    gender: "Female",
    skinType: "Normal",
    allergies: "None",
    totalVisits: 11,
    totalSpent: 7850,
    lastVisit: "2026-09-01",
    notes: "Regular Profhilo & Juvederm touchups. Always buys SkinCeuticals CE Ferulic.",
    createdAt: "2023-08-14",
  },
];

export const seedAppointments: Appointment[] = [
  {
    appointmentId: "apt-101",
    customerName: "Victoria Sterling",
    customerPhone: "+1 (555) 901-2345",
    customerEmail: "victoria.sterling@beverly.com",
    procedureId: "trt-002",
    procedureName: "Botox Cosmetic (3 Target Areas)",
    employeeId: "emp-001",
    employeeName: "Sheraz khan",
    appointmentDate: "2026-09-05",
    appointmentTime: "10:30",
    status: "confirmed",
    createdBy: "usr-reception",
    price: 480,
    notes: "Follow up touch-up for forehead lines.",
  },
  {
    appointmentId: "apt-102",
    customerName: "Camilla Rodriguez",
    customerPhone: "+1 (555) 723-4567",
    customerEmail: "camilla.r@studio.design",
    procedureId: "trt-001",
    procedureName: "HydraFacial Platinum Luxe",
    employeeId: "emp-003",
    employeeName: "Sophia Laurent",
    appointmentDate: "2026-09-05",
    appointmentTime: "11:45",
    status: "in-progress",
    createdBy: "usr-reception",
    price: 295,
    notes: "Include red LED light therapy booster.",
  },
  {
    appointmentId: "apt-103",
    customerName: "Julian Montgomery",
    customerPhone: "+1 (555) 812-3456",
    customerEmail: "j.montgomery@venture.io",
    procedureId: "trt-004",
    procedureName: "Fractional CO2 Laser Resurfacing",
    employeeId: "emp-002",
    employeeName: "Dr. Marcus Chen, M.D.",
    appointmentDate: "2026-09-05",
    appointmentTime: "14:00",
    status: "scheduled",
    createdBy: "usr-reception",
    price: 890,
    notes: "Pre-numbing cream applied 30 min prior.",
  },
  {
    appointmentId: "apt-104",
    customerName: "Liam O'Connor",
    customerPhone: "+1 (555) 634-5678",
    customerEmail: "liam.oconnor@media.net",
    procedureId: "trt-005",
    procedureName: "PRP Vampire Facial & Microneedling",
    employeeId: "emp-004",
    employeeName: "Maya Patel, R.N.",
    appointmentDate: "2026-09-05",
    appointmentTime: "16:00",
    status: "scheduled",
    createdBy: "usr-reception",
    price: 580,
    notes: "Blood draw for PRP in treatment room 3.",
  },
  {
    appointmentId: "apt-105",
    customerName: "Seraphina Thorne",
    customerPhone: "+1 (555) 545-6789",
    customerEmail: "seraphina@thorne-estates.com",
    procedureId: "trt-008",
    procedureName: "Profhilo Bio-Remodeling Hydration",
    employeeId: "emp-001",
    employeeName: "Sheraz khan",
    appointmentDate: "2026-09-06",
    appointmentTime: "11:00",
    status: "scheduled",
    createdBy: "usr-reception",
    price: 520,
    notes: "Session 2 of 2 protocol.",
  },
];

export const seedPharmacy: PharmacyItem[] = [
  {
    itemId: "phm-001",
    name: "Botox Cosmetic 100U Vials",
    category: "Injectables & Toxins",
    quantity: 14,
    unit: "vials",
    minThreshold: 5,
    costPrice: 220,
    sellingPrice: 480,
    expiryDate: "2027-04-30",
    supplier: "Allergan Aesthetics Direct",
    batchNumber: "AL-89211",
  },
  {
    itemId: "phm-002",
    name: "Juvederm Voluma XC (1ml Syringe)",
    category: "Injectables & Toxins",
    quantity: 18,
    unit: "syringes",
    minThreshold: 6,
    costPrice: 290,
    sellingPrice: 750,
    expiryDate: "2027-02-15",
    supplier: "AbbVie / Allergan Medical",
    batchNumber: "JV-44901",
  },
  {
    itemId: "phm-003",
    name: "SkinCeuticals C E Ferulic (30ml)",
    category: "Skincare & Cosmeceuticals",
    quantity: 24,
    unit: "bottles",
    minThreshold: 8,
    costPrice: 95,
    sellingPrice: 182,
    expiryDate: "2027-08-01",
    supplier: "L'Oréal Dermatological Beauty",
    batchNumber: "SC-30219",
  },
  {
    itemId: "phm-004",
    name: "Heliocare 360 Mineral Tolerance Fluid SPF 50",
    category: "Post-Procedure Care",
    quantity: 4, // Low stock indicator
    unit: "tubes",
    minThreshold: 10,
    costPrice: 22,
    sellingPrice: 48,
    expiryDate: "2027-06-30",
    supplier: "Cantabria Labs",
    batchNumber: "HC-77124",
  },
  {
    itemId: "phm-005",
    name: "Profhilo H+L (2ml Pre-filled Syringe)",
    category: "Injectables & Toxins",
    quantity: 8,
    unit: "syringes",
    minThreshold: 4,
    costPrice: 210,
    sellingPrice: 520,
    expiryDate: "2027-01-20",
    supplier: "IBSA Derma",
    batchNumber: "IB-90234",
  },
  {
    itemId: "phm-006",
    name: "HydraFacial Deluxe Vortex Booster Kits",
    category: "Supplies & Consumables",
    quantity: 32,
    unit: "kits",
    minThreshold: 12,
    costPrice: 45,
    sellingPrice: 95,
    expiryDate: "2027-11-10",
    supplier: "BeautyHealth Co.",
    batchNumber: "HF-66321",
  },
  {
    itemId: "phm-007",
    name: "Avene Cicalfate+ Restorative Protective Cream (100ml)",
    category: "Post-Procedure Care",
    quantity: 20,
    unit: "tubes",
    minThreshold: 8,
    costPrice: 14,
    sellingPrice: 32,
    expiryDate: "2027-09-15",
    supplier: "Pierre Fabre Dermo-Cosmetique",
    batchNumber: "AV-19832",
  },
];

export const seedSales: Sale[] = [
  {
    saleId: "sal-001",
    invoiceNumber: "INV-2026-901",
    appointmentId: "apt-099",
    customerName: "Victoria Sterling",
    customerPhone: "+1 (555) 901-2345",
    procedureId: "trt-003",
    procedureName: "Juvederm Voluma Cheek & Jaw Contour",
    amount: 750,
    discount: 50,
    netAmount: 700,
    paymentMethod: "credit_card",
    saleDate: "2026-09-02",
    recordedBy: "Isabella Rossi",
    notes: "VIP Member loyalty discount applied.",
  },
  {
    saleId: "sal-002",
    invoiceNumber: "INV-2026-902",
    customerName: "Seraphina Thorne",
    customerPhone: "+1 (555) 545-6789",
    procedureId: "trt-008",
    procedureName: "Profhilo Bio-Remodeling Hydration",
    amount: 520,
    discount: 0,
    netAmount: 520,
    paymentMethod: "credit_card",
    saleDate: "2026-09-01",
    recordedBy: "Alexander Wright",
  },
  {
    saleId: "sal-003",
    invoiceNumber: "INV-2026-903",
    customerName: "Julian Montgomery",
    customerPhone: "+1 (555) 812-3456",
    procedureId: "trt-004",
    procedureName: "Fractional CO2 Laser Resurfacing",
    amount: 890,
    discount: 0,
    netAmount: 890,
    paymentMethod: "bank_transfer",
    saleDate: "2026-08-28",
    recordedBy: "Alexander Wright",
  },
  {
    saleId: "sal-004",
    invoiceNumber: "INV-2026-904",
    customerName: "Camilla Rodriguez",
    customerPhone: "+1 (555) 723-4567",
    procedureId: "trt-001",
    procedureName: "HydraFacial Platinum Luxe",
    amount: 295,
    discount: 25,
    netAmount: 270,
    paymentMethod: "cash",
    saleDate: "2026-08-27",
    recordedBy: "Isabella Rossi",
  },
  {
    saleId: "sal-005",
    invoiceNumber: "INV-2026-905",
    customerName: "Liam O'Connor",
    customerPhone: "+1 (555) 634-5678",
    procedureId: "trt-007",
    procedureName: "Laser Hair Reduction (Full Legs & Underarms)",
    amount: 380,
    discount: 0,
    netAmount: 380,
    paymentMethod: "credit_card",
    saleDate: "2026-08-20",
    recordedBy: "Isabella Rossi",
  },
  {
    saleId: "sal-006",
    invoiceNumber: "INV-2026-906",
    customerName: "Victoria Sterling",
    customerPhone: "+1 (555) 901-2345",
    procedureId: "trt-001",
    procedureName: "HydraFacial Platinum Luxe",
    amount: 295,
    discount: 0,
    netAmount: 295,
    paymentMethod: "credit_card",
    saleDate: "2026-08-15",
    recordedBy: "Isabella Rossi",
  },
  {
    saleId: "sal-007",
    invoiceNumber: "INV-2026-907",
    customerName: "Julian Montgomery",
    customerPhone: "+1 (555) 812-3456",
    procedureId: "trt-005",
    procedureName: "PRP Vampire Facial & Microneedling",
    amount: 580,
    discount: 0,
    netAmount: 580,
    paymentMethod: "credit_card",
    saleDate: "2026-08-10",
    recordedBy: "Alexander Wright",
  },
];

export const seedExpenses: Expense[] = [
  {
    expenseId: "exp-001",
    category: "Rent & Premises",
    description: "Monthly Beverly Hills Suite Lease & Building Maintenance",
    amount: 5200,
    expenseDate: "2026-09-01",
    recordedBy: "Alexander Wright",
    vendor: "Rodeo Luxury Properties LLC",
  },
  {
    expenseId: "exp-002",
    category: "Medical Supplies & Serums",
    description: "Restock Allergan Botox 100U (10 vials) & Juvederm Voluma",
    amount: 3800,
    expenseDate: "2026-08-29",
    recordedBy: "Alexander Wright",
    vendor: "Allergan Pharmaceuticals Supply",
  },
  {
    expenseId: "exp-003",
    category: "Marketing & Social Media",
    description: "Google Ads Aesthetic Search & Instagram Influencer Campaign",
    amount: 1450,
    expenseDate: "2026-08-25",
    recordedBy: "Alexander Wright",
    vendor: "Meta & Google Ads",
  },
  {
    expenseId: "exp-004",
    category: "Utilities & Internet",
    description: "High-speed Fiber Internet & Clinic Power/Cooling",
    amount: 680,
    expenseDate: "2026-08-22",
    recordedBy: "Alexander Wright",
    vendor: "SoCal Edison & AT&T Business",
  },
  {
    expenseId: "exp-005",
    category: "Equipment & Maintenance",
    description: "Annual Optical Calibration for Fractional CO2 Laser Unit",
    amount: 950,
    expenseDate: "2026-08-18",
    recordedBy: "Alexander Wright",
    vendor: "Candela Laser Tech Services",
  },
];

export const seedAttendance: AttendanceRecord[] = [
  // Today's attendance
  {
    attendanceId: "att-today-001",
    employeeId: "emp-001",
    employeeName: "Sheraz khan",
    date: "2026-09-05",
    status: "present",
    checkIn: "08:55",
    checkOut: "18:05",
    markedBy: "Alexander Wright",
  },
  {
    attendanceId: "att-today-002",
    employeeId: "emp-002",
    employeeName: "Dr. Marcus Chen, M.D.",
    date: "2026-09-05",
    status: "present",
    checkIn: "09:50",
    checkOut: "19:00",
    markedBy: "Alexander Wright",
  },
  {
    attendanceId: "att-today-003",
    employeeId: "emp-003",
    employeeName: "Sophia Laurent",
    date: "2026-09-05",
    status: "present",
    checkIn: "08:58",
    checkOut: "17:35",
    markedBy: "Alexander Wright",
  },
  {
    attendanceId: "att-today-004",
    employeeId: "emp-004",
    employeeName: "Maya Patel, R.N.",
    date: "2026-09-05",
    status: "present",
    checkIn: "09:02",
    checkOut: "18:00",
    markedBy: "Alexander Wright",
  },
  {
    attendanceId: "att-today-005",
    employeeId: "emp-005",
    employeeName: "Alexander Wright",
    date: "2026-09-05",
    status: "present",
    checkIn: "08:25",
    checkOut: "17:40",
    markedBy: "Alexander Wright",
  },
  {
    attendanceId: "att-today-006",
    employeeId: "emp-006",
    employeeName: "Isabella Rossi",
    date: "2026-09-05",
    status: "present",
    checkIn: "08:28",
    checkOut: "17:05",
    markedBy: "Alexander Wright",
  },
  // Yesterday's attendance
  {
    attendanceId: "att-yest-001",
    employeeId: "emp-001",
    employeeName: "Sheraz khan",
    date: "2026-09-04",
    status: "present",
    checkIn: "08:50",
    checkOut: "18:10",
    markedBy: "Alexander Wright",
  },
  {
    attendanceId: "att-yest-002",
    employeeId: "emp-002",
    employeeName: "Dr. Marcus Chen, M.D.",
    date: "2026-09-04",
    status: "present",
    checkIn: "09:55",
    checkOut: "19:05",
    markedBy: "Alexander Wright",
  },
  {
    attendanceId: "att-yest-003",
    employeeId: "emp-003",
    employeeName: "Sophia Laurent",
    date: "2026-09-04",
    status: "leave",
    markedBy: "Alexander Wright",
    remarks: "Approved annual personal leave.",
  },
  {
    attendanceId: "att-yest-004",
    employeeId: "emp-004",
    employeeName: "Maya Patel, R.N.",
    date: "2026-09-04",
    status: "present",
    checkIn: "09:00",
    checkOut: "18:00",
    markedBy: "Alexander Wright",
  },
  {
    attendanceId: "att-yest-005",
    employeeId: "emp-005",
    employeeName: "Alexander Wright",
    date: "2026-09-04",
    status: "present",
    checkIn: "08:30",
    checkOut: "17:30",
    markedBy: "Alexander Wright",
  },
  {
    attendanceId: "att-yest-006",
    employeeId: "emp-006",
    employeeName: "Isabella Rossi",
    date: "2026-09-04",
    status: "present",
    checkIn: "08:30",
    checkOut: "17:00",
    markedBy: "Alexander Wright",
  },
];

export const seedSalaries: SalaryRecord[] = [
  {
    salaryId: "sal-emp-001-2026-08",
    employeeId: "emp-001",
    employeeName: "Sheraz khan",
    designation: "Lead Aesthetic Physician",
    month: "2026-08",
    baseSalary: 9500,
    workingDays: 26,
    presentDays: 26,
    absentDays: 0,
    leaveDays: 0,
    dailyRate: 365.38,
    deductions: 0,
    bonus: 500,
    netPay: 10000,
    status: "paid",
    paymentDate: "2026-08-31",
    paymentMethod: "bank_transfer",
    recordedBy: "Alexander Wright",
    payslipNumber: "PAY-202608-0001",
    remarks: "Full attendance plus quarterly performance incentive.",
  },
  {
    salaryId: "sal-emp-002-2026-08",
    employeeId: "emp-002",
    employeeName: "Dr. Marcus Chen, M.D.",
    designation: "Cosmetic Dermatologist",
    month: "2026-08",
    baseSalary: 9000,
    workingDays: 26,
    presentDays: 25,
    absentDays: 1,
    leaveDays: 0,
    dailyRate: 346.15,
    deductions: 346.15,
    bonus: 0,
    netPay: 8653.85,
    status: "paid",
    paymentDate: "2026-08-31",
    paymentMethod: "bank_transfer",
    recordedBy: "Alexander Wright",
    payslipNumber: "PAY-202608-0002",
    remarks: "1 day unexcused absence deduction.",
  },
  {
    salaryId: "sal-emp-003-2026-08",
    employeeId: "emp-003",
    employeeName: "Sophia Laurent",
    designation: "Senior Aesthetician",
    month: "2026-08",
    baseSalary: 4500,
    workingDays: 26,
    presentDays: 26,
    absentDays: 0,
    leaveDays: 0,
    dailyRate: 173.08,
    deductions: 0,
    bonus: 250,
    netPay: 4750,
    status: "paid",
    paymentDate: "2026-08-31",
    paymentMethod: "bank_transfer",
    recordedBy: "Alexander Wright",
    payslipNumber: "PAY-202608-0003",
    remarks: "HydraFacial client satisfaction bonus.",
  },
  {
    salaryId: "sal-emp-004-2026-08",
    employeeId: "emp-004",
    employeeName: "Maya Patel, R.N.",
    designation: "Registered Aesthetic Nurse",
    month: "2026-08",
    baseSalary: 4800,
    workingDays: 26,
    presentDays: 26,
    absentDays: 0,
    leaveDays: 0,
    dailyRate: 184.62,
    deductions: 0,
    bonus: 200,
    netPay: 5000,
    status: "paid",
    paymentDate: "2026-08-31",
    paymentMethod: "bank_transfer",
    recordedBy: "Alexander Wright",
    payslipNumber: "PAY-202608-0004",
  },
  {
    salaryId: "sal-emp-005-2026-08",
    employeeId: "emp-005",
    employeeName: "Alexander Wright",
    designation: "Clinic Manager",
    month: "2026-08",
    baseSalary: 5800,
    workingDays: 26,
    presentDays: 26,
    absentDays: 0,
    leaveDays: 0,
    dailyRate: 223.08,
    deductions: 0,
    bonus: 0,
    netPay: 5800,
    status: "paid",
    paymentDate: "2026-08-31",
    paymentMethod: "bank_transfer",
    recordedBy: "Alexander Wright",
    payslipNumber: "PAY-202608-0005",
  },
  {
    salaryId: "sal-emp-006-2026-08",
    employeeId: "emp-006",
    employeeName: "Isabella Rossi",
    designation: "Front Desk Receptionist",
    month: "2026-08",
    baseSalary: 3400,
    workingDays: 26,
    presentDays: 26,
    absentDays: 0,
    leaveDays: 0,
    dailyRate: 130.77,
    deductions: 0,
    bonus: 100,
    netPay: 3500,
    status: "paid",
    paymentDate: "2026-08-31",
    paymentMethod: "bank_transfer",
    recordedBy: "Alexander Wright",
    payslipNumber: "PAY-202608-0006",
  },
];
